export const DISTRICTS = [
  { id: "d0", city: "강원" },
  { id: "d1", city: "경기" },
  { id: "d2", city: "경남" },
  { id: "d3", city: "경북" },
  { id: "d4", city: "광주" },
  { id: "d5", city: "대구" },
  { id: "d6", city: "대전" },
  { id: "d7", city: "부산" },
  { id: "d8", city: "서울" },
  { id: "d9", city: "세종" },
  { id: "d10", city: "울산" },
  { id: "d11", city: "인천" },
  { id: "d12", city: "전남" },
  { id: "d13", city: "전북" },
  { id: "d14", city: "제주" },
  { id: "d15", city: "충남" },
  { id: "d16", city: "충북" },
]